### ISSUE TITLE
1.19.4 Build?

### ISSUE THREAD

**Issue by Sophed** [admin-else/MicroBloat#3]

**Comment by admin-else** [comment]
Iam sorry but i kinda forgot about this mod mojang did a rewrite of the gui system which trashed 90% of my code and i dont know if i want to fix all that since i have other stuff do. I Can cut some features.
I dont know if people only downloaded the mod minimal menu stuff or also for my features (if u only want minimal menu it wont take that long).
Let me know.

**Comment by Sophed** [comment]
Yeah I was mainly looking for the minimal menu stuff, I found an alternative in FancyMenu but I think a newer build would still be super useful for others. I do appreciate your efforts though keep it up <3

**Comment by Cabbasca** [comment]
I just updated it to 1.20.1
<https://github.com/Cabbasca/MicroBloat-But-Updated>

**Comment by Cabbasca** [comment]
I can fix the telemetry stuff later but it doesn't seem like that's what most people use the mod for
